name: Build IMS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Remove conflicting classes from android.jar
        run: |
          zip -d ./platforms/android-33/android.jar \
          android/telephony/ims/feature/MmTelFeature.class \
          android/telephony/ims/feature/MmTelFeature\$MmTelCapabilities.class

      - name: Grant execute permission for build.sh
        run: chmod +x build.sh

      - name: Run build script
        run: ./build.sh
